var annotated =
[
    [ "Eigen", "namespaceEigen.html", [
      [ "doxygen", null, [
        [ "dense_xpr_base_dispatcher", "structEigen_1_1doxygen_1_1dense__xpr__base__dispatcher.html", null ],
        [ "dense_xpr_base_dispatcher< Array< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >", "structEigen_1_1doxygen_1_1dense__xpr__base__dispatcher_3_01Array_3_01__Scalar_00_01__Rows_00_01_9f66d076f8f04907f9f0093247d3c377.html", null ],
        [ "dense_xpr_base_dispatcher< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >", "structEigen_1_1doxygen_1_1dense__xpr__base__dispatcher_3_01Matrix_3_01__Scalar_00_01__Rows_00_0116fa1ae814876cf66b62915b437740e6.html", null ]
      ] ],
      [ "symbolic", "namespaceEigen_1_1symbolic.html", [
        [ "BaseExpr", "classEigen_1_1symbolic_1_1BaseExpr.html", "classEigen_1_1symbolic_1_1BaseExpr" ],
        [ "SymbolExpr", "classEigen_1_1symbolic_1_1SymbolExpr.html", "classEigen_1_1symbolic_1_1SymbolExpr" ],
        [ "SymbolValue", "classEigen_1_1symbolic_1_1SymbolValue.html", "classEigen_1_1symbolic_1_1SymbolValue" ]
      ] ],
      [ "aligned_allocator", "classEigen_1_1aligned__allocator.html", null ],
      [ "AlignedBox", "classEigen_1_1AlignedBox.html", "classEigen_1_1AlignedBox" ],
      [ "AMDOrdering", "classEigen_1_1AMDOrdering.html", "classEigen_1_1AMDOrdering" ],
      [ "AngleAxis", "classEigen_1_1AngleAxis.html", "classEigen_1_1AngleAxis" ],
      [ "ArithmeticSequence", "classEigen_1_1ArithmeticSequence.html", "classEigen_1_1ArithmeticSequence" ],
      [ "Array", "classEigen_1_1Array.html", "classEigen_1_1Array" ],
      [ "ArrayBase", "classEigen_1_1ArrayBase.html", "classEigen_1_1ArrayBase" ],
      [ "ArrayWrapper", "classEigen_1_1ArrayWrapper.html", "classEigen_1_1ArrayWrapper" ],
      [ "ArrayXpr", "structEigen_1_1ArrayXpr.html", null ],
      [ "BDCSVD", "classEigen_1_1BDCSVD.html", "classEigen_1_1BDCSVD" ],
      [ "BiCGSTAB", "classEigen_1_1BiCGSTAB.html", "classEigen_1_1BiCGSTAB" ],
      [ "Block", "classEigen_1_1Block.html", "classEigen_1_1Block" ],
      [ "BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >", "classEigen_1_1BlockImpl_3_01XprType_00_01BlockRows_00_01BlockCols_00_01InnerPanel_00_01Sparse_01_4.html", "classEigen_1_1BlockImpl_3_01XprType_00_01BlockRows_00_01BlockCols_00_01InnerPanel_00_01Sparse_01_4" ],
      [ "CholmodBase", "classEigen_1_1CholmodBase.html", "classEigen_1_1CholmodBase" ],
      [ "CholmodDecomposition", "classEigen_1_1CholmodDecomposition.html", null ],
      [ "CholmodSimplicialLDLT", "classEigen_1_1CholmodSimplicialLDLT.html", null ],
      [ "CholmodSimplicialLLT", "classEigen_1_1CholmodSimplicialLLT.html", null ],
      [ "CholmodSupernodalLLT", "classEigen_1_1CholmodSupernodalLLT.html", null ],
      [ "COLAMDOrdering", "classEigen_1_1COLAMDOrdering.html", "classEigen_1_1COLAMDOrdering" ],
      [ "ColPivHouseholderQR", "classEigen_1_1ColPivHouseholderQR.html", "classEigen_1_1ColPivHouseholderQR" ],
      [ "CommaInitializer", "structEigen_1_1CommaInitializer.html", "structEigen_1_1CommaInitializer" ],
      [ "CompleteOrthogonalDecomposition", "classEigen_1_1CompleteOrthogonalDecomposition.html", "classEigen_1_1CompleteOrthogonalDecomposition" ],
      [ "ComplexEigenSolver", "classEigen_1_1ComplexEigenSolver.html", "classEigen_1_1ComplexEigenSolver" ],
      [ "ComplexSchur", "classEigen_1_1ComplexSchur.html", "classEigen_1_1ComplexSchur" ],
      [ "ConjugateGradient", "classEigen_1_1ConjugateGradient.html", "classEigen_1_1ConjugateGradient" ],
      [ "CwiseBinaryOp", "classEigen_1_1CwiseBinaryOp.html", "classEigen_1_1CwiseBinaryOp" ],
      [ "CwiseNullaryOp", "classEigen_1_1CwiseNullaryOp.html", "classEigen_1_1CwiseNullaryOp" ],
      [ "CwiseTernaryOp", "classEigen_1_1CwiseTernaryOp.html", "classEigen_1_1CwiseTernaryOp" ],
      [ "CwiseUnaryOp", "classEigen_1_1CwiseUnaryOp.html", "classEigen_1_1CwiseUnaryOp" ],
      [ "CwiseUnaryView", "classEigen_1_1CwiseUnaryView.html", "classEigen_1_1CwiseUnaryView" ],
      [ "Dense", "structEigen_1_1Dense.html", null ],
      [ "DenseBase", "classEigen_1_1DenseBase.html", "classEigen_1_1DenseBase" ],
      [ "DenseCoeffsBase< Derived, DirectAccessors >", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01DirectAccessors_01_4.html", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01DirectAccessors_01_4" ],
      [ "DenseCoeffsBase< Derived, DirectWriteAccessors >", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01DirectWriteAccessors_01_4.html", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01DirectWriteAccessors_01_4" ],
      [ "DenseCoeffsBase< Derived, ReadOnlyAccessors >", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01ReadOnlyAccessors_01_4" ],
      [ "DenseCoeffsBase< Derived, WriteAccessors >", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01WriteAccessors_01_4.html", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01WriteAccessors_01_4" ],
      [ "Diagonal", "classEigen_1_1Diagonal.html", null ],
      [ "DiagonalMatrix", "classEigen_1_1DiagonalMatrix.html", "classEigen_1_1DiagonalMatrix" ],
      [ "DiagonalPreconditioner", "classEigen_1_1DiagonalPreconditioner.html", null ],
      [ "DiagonalWrapper", "classEigen_1_1DiagonalWrapper.html", "classEigen_1_1DiagonalWrapper" ],
      [ "EigenBase", "structEigen_1_1EigenBase.html", "structEigen_1_1EigenBase" ],
      [ "EigenSolver", "classEigen_1_1EigenSolver.html", "classEigen_1_1EigenSolver" ],
      [ "ForceAlignedAccess", "classEigen_1_1ForceAlignedAccess.html", null ],
      [ "FullPivHouseholderQR", "classEigen_1_1FullPivHouseholderQR.html", "classEigen_1_1FullPivHouseholderQR" ],
      [ "FullPivLU", "classEigen_1_1FullPivLU.html", "classEigen_1_1FullPivLU" ],
      [ "GeneralizedEigenSolver", "classEigen_1_1GeneralizedEigenSolver.html", "classEigen_1_1GeneralizedEigenSolver" ],
      [ "GeneralizedSelfAdjointEigenSolver", "classEigen_1_1GeneralizedSelfAdjointEigenSolver.html", "classEigen_1_1GeneralizedSelfAdjointEigenSolver" ],
      [ "HessenbergDecomposition", "classEigen_1_1HessenbergDecomposition.html", "classEigen_1_1HessenbergDecomposition" ],
      [ "Homogeneous", "classEigen_1_1Homogeneous.html", null ],
      [ "HouseholderQR", "classEigen_1_1HouseholderQR.html", "classEigen_1_1HouseholderQR" ],
      [ "HouseholderSequence", "classEigen_1_1HouseholderSequence.html", "classEigen_1_1HouseholderSequence" ],
      [ "Hyperplane", "classEigen_1_1Hyperplane.html", "classEigen_1_1Hyperplane" ],
      [ "IdentityPreconditioner", "classEigen_1_1IdentityPreconditioner.html", null ],
      [ "IncompleteCholesky", "classEigen_1_1IncompleteCholesky.html", "classEigen_1_1IncompleteCholesky" ],
      [ "IncompleteLUT", "classEigen_1_1IncompleteLUT.html", "classEigen_1_1IncompleteLUT" ],
      [ "IndexedView", "classEigen_1_1IndexedView.html", "classEigen_1_1IndexedView" ],
      [ "InnerStride", "classEigen_1_1InnerStride.html", null ],
      [ "Inverse", "classEigen_1_1Inverse.html", null ],
      [ "IOFormat", "structEigen_1_1IOFormat.html", "structEigen_1_1IOFormat" ],
      [ "IterativeSolverBase", "classEigen_1_1IterativeSolverBase.html", "classEigen_1_1IterativeSolverBase" ],
      [ "JacobiRotation", "classEigen_1_1JacobiRotation.html", "classEigen_1_1JacobiRotation" ],
      [ "JacobiSVD", "classEigen_1_1JacobiSVD.html", "classEigen_1_1JacobiSVD" ],
      [ "LDLT", "classEigen_1_1LDLT.html", "classEigen_1_1LDLT" ],
      [ "LeastSquareDiagonalPreconditioner", "classEigen_1_1LeastSquareDiagonalPreconditioner.html", null ],
      [ "LeastSquaresConjugateGradient", "classEigen_1_1LeastSquaresConjugateGradient.html", "classEigen_1_1LeastSquaresConjugateGradient" ],
      [ "LLT", "classEigen_1_1LLT.html", "classEigen_1_1LLT" ],
      [ "Map", "classEigen_1_1Map.html", "classEigen_1_1Map" ],
      [ "Map< const Quaternion< _Scalar >, _Options >", "classEigen_1_1Map_3_01const_01Quaternion_3_01__Scalar_01_4_00_01__Options_01_4.html", "classEigen_1_1Map_3_01const_01Quaternion_3_01__Scalar_01_4_00_01__Options_01_4" ],
      [ "Map< Quaternion< _Scalar >, _Options >", "classEigen_1_1Map_3_01Quaternion_3_01__Scalar_01_4_00_01__Options_01_4.html", "classEigen_1_1Map_3_01Quaternion_3_01__Scalar_01_4_00_01__Options_01_4" ],
      [ "Map< SparseMatrixType >", "classEigen_1_1Map_3_01SparseMatrixType_01_4.html", "classEigen_1_1Map_3_01SparseMatrixType_01_4" ],
      [ "MapBase< Derived, ReadOnlyAccessors >", "classEigen_1_1MapBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html", "classEigen_1_1MapBase_3_01Derived_00_01ReadOnlyAccessors_01_4" ],
      [ "MapBase< Derived, WriteAccessors >", "classEigen_1_1MapBase_3_01Derived_00_01WriteAccessors_01_4.html", null ],
      [ "MappedSparseMatrix", "classEigen_1_1MappedSparseMatrix.html", "classEigen_1_1MappedSparseMatrix" ],
      [ "Matrix", "classEigen_1_1Matrix.html", "classEigen_1_1Matrix" ],
      [ "MatrixBase", "classEigen_1_1MatrixBase.html", "classEigen_1_1MatrixBase" ],
      [ "MatrixWrapper", "classEigen_1_1MatrixWrapper.html", "classEigen_1_1MatrixWrapper" ],
      [ "MatrixXpr", "structEigen_1_1MatrixXpr.html", null ],
      [ "MetisOrdering", "classEigen_1_1MetisOrdering.html", null ],
      [ "NaturalOrdering", "classEigen_1_1NaturalOrdering.html", "classEigen_1_1NaturalOrdering" ],
      [ "NestByValue", "classEigen_1_1NestByValue.html", null ],
      [ "NoAlias", "classEigen_1_1NoAlias.html", null ],
      [ "NumTraits", "structEigen_1_1NumTraits.html", null ],
      [ "OuterStride", "classEigen_1_1OuterStride.html", null ],
      [ "ParametrizedLine", "classEigen_1_1ParametrizedLine.html", "classEigen_1_1ParametrizedLine" ],
      [ "PardisoLDLT", "classEigen_1_1PardisoLDLT.html", null ],
      [ "PardisoLLT", "classEigen_1_1PardisoLLT.html", null ],
      [ "PardisoLU", "classEigen_1_1PardisoLU.html", "classEigen_1_1PardisoLU" ],
      [ "PartialPivLU", "classEigen_1_1PartialPivLU.html", "classEigen_1_1PartialPivLU" ],
      [ "PartialReduxExpr", "classEigen_1_1PartialReduxExpr.html", null ],
      [ "PastixLDLT", "classEigen_1_1PastixLDLT.html", "classEigen_1_1PastixLDLT" ],
      [ "PastixLLT", "classEigen_1_1PastixLLT.html", "classEigen_1_1PastixLLT" ],
      [ "PastixLU", "classEigen_1_1PastixLU.html", "classEigen_1_1PastixLU" ],
      [ "PermutationBase", "classEigen_1_1PermutationBase.html", "classEigen_1_1PermutationBase" ],
      [ "PermutationMatrix", "classEigen_1_1PermutationMatrix.html", "classEigen_1_1PermutationMatrix" ],
      [ "PermutationStorage", "structEigen_1_1PermutationStorage.html", null ],
      [ "PermutationWrapper", "classEigen_1_1PermutationWrapper.html", "classEigen_1_1PermutationWrapper" ],
      [ "PlainObjectBase", "classEigen_1_1PlainObjectBase.html", "classEigen_1_1PlainObjectBase" ],
      [ "Product", "classEigen_1_1Product.html", null ],
      [ "Quaternion", "classEigen_1_1Quaternion.html", "classEigen_1_1Quaternion" ],
      [ "QuaternionBase", "classEigen_1_1QuaternionBase.html", "classEigen_1_1QuaternionBase" ],
      [ "RealQZ", "classEigen_1_1RealQZ.html", "classEigen_1_1RealQZ" ],
      [ "RealSchur", "classEigen_1_1RealSchur.html", "classEigen_1_1RealSchur" ],
      [ "Ref", "classEigen_1_1Ref.html", "classEigen_1_1Ref" ],
      [ "Ref< SparseMatrixType, Options >", "classEigen_1_1Ref_3_01SparseMatrixType_00_01Options_01_4.html", "classEigen_1_1Ref_3_01SparseMatrixType_00_01Options_01_4" ],
      [ "Ref< SparseVectorType >", "classEigen_1_1Ref_3_01SparseVectorType_01_4.html", "classEigen_1_1Ref_3_01SparseVectorType_01_4" ],
      [ "Replicate", "classEigen_1_1Replicate.html", null ],
      [ "Reshaped", "classEigen_1_1Reshaped.html", "classEigen_1_1Reshaped" ],
      [ "Reverse", "classEigen_1_1Reverse.html", null ],
      [ "Rotation2D", "classEigen_1_1Rotation2D.html", "classEigen_1_1Rotation2D" ],
      [ "RotationBase", "classEigen_1_1RotationBase.html", "classEigen_1_1RotationBase" ],
      [ "ScalarBinaryOpTraits", "structEigen_1_1ScalarBinaryOpTraits.html", null ],
      [ "Select", "classEigen_1_1Select.html", null ],
      [ "SelfAdjointEigenSolver", "classEigen_1_1SelfAdjointEigenSolver.html", "classEigen_1_1SelfAdjointEigenSolver" ],
      [ "SelfAdjointView", "classEigen_1_1SelfAdjointView.html", "classEigen_1_1SelfAdjointView" ],
      [ "SimplicialCholesky", "classEigen_1_1SimplicialCholesky.html", "classEigen_1_1SimplicialCholesky" ],
      [ "SimplicialCholeskyBase", "classEigen_1_1SimplicialCholeskyBase.html", "classEigen_1_1SimplicialCholeskyBase" ],
      [ "SimplicialLDLT", "classEigen_1_1SimplicialLDLT.html", "classEigen_1_1SimplicialLDLT" ],
      [ "SimplicialLLT", "classEigen_1_1SimplicialLLT.html", "classEigen_1_1SimplicialLLT" ],
      [ "Solve", "classEigen_1_1Solve.html", null ],
      [ "SolverBase", "classEigen_1_1SolverBase.html", "classEigen_1_1SolverBase" ],
      [ "SolverStorage", "structEigen_1_1SolverStorage.html", null ],
      [ "SolveWithGuess", "classEigen_1_1SolveWithGuess.html", null ],
      [ "Sparse", "structEigen_1_1Sparse.html", null ],
      [ "SparseCompressedBase", "classEigen_1_1SparseCompressedBase.html", "classEigen_1_1SparseCompressedBase" ],
      [ "SparseLU", "classEigen_1_1SparseLU.html", "classEigen_1_1SparseLU" ],
      [ "SparseMapBase< Derived, ReadOnlyAccessors >", "classEigen_1_1SparseMapBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html", "classEigen_1_1SparseMapBase_3_01Derived_00_01ReadOnlyAccessors_01_4" ],
      [ "SparseMapBase< Derived, WriteAccessors >", "classEigen_1_1SparseMapBase_3_01Derived_00_01WriteAccessors_01_4.html", "classEigen_1_1SparseMapBase_3_01Derived_00_01WriteAccessors_01_4" ],
      [ "SparseMatrix", "classEigen_1_1SparseMatrix.html", "classEigen_1_1SparseMatrix" ],
      [ "SparseMatrixBase", "classEigen_1_1SparseMatrixBase.html", "classEigen_1_1SparseMatrixBase" ],
      [ "SparseQR", "classEigen_1_1SparseQR.html", "classEigen_1_1SparseQR" ],
      [ "SparseSelfAdjointView", "classEigen_1_1SparseSelfAdjointView.html", "classEigen_1_1SparseSelfAdjointView" ],
      [ "SparseSolverBase", "classEigen_1_1SparseSolverBase.html", "classEigen_1_1SparseSolverBase" ],
      [ "SparseVector", "classEigen_1_1SparseVector.html", "classEigen_1_1SparseVector" ],
      [ "SparseView", "classEigen_1_1SparseView.html", "classEigen_1_1SparseView" ],
      [ "SPQR", "classEigen_1_1SPQR.html", "classEigen_1_1SPQR" ],
      [ "Stride", "classEigen_1_1Stride.html", "classEigen_1_1Stride" ],
      [ "SuperILU", "classEigen_1_1SuperILU.html", "classEigen_1_1SuperILU" ],
      [ "SuperLU", "classEigen_1_1SuperLU.html", "classEigen_1_1SuperLU" ],
      [ "SuperLUBase", "classEigen_1_1SuperLUBase.html", "classEigen_1_1SuperLUBase" ],
      [ "SVDBase", "classEigen_1_1SVDBase.html", "classEigen_1_1SVDBase" ],
      [ "Transform", "classEigen_1_1Transform.html", "classEigen_1_1Transform" ],
      [ "Translation", "classEigen_1_1Translation.html", "classEigen_1_1Translation" ],
      [ "Transpose", "classEigen_1_1Transpose.html", "classEigen_1_1Transpose" ],
      [ "Transpositions", "classEigen_1_1Transpositions.html", "classEigen_1_1Transpositions" ],
      [ "TranspositionsStorage", "structEigen_1_1TranspositionsStorage.html", null ],
      [ "TriangularBase", "classEigen_1_1TriangularBase.html", "classEigen_1_1TriangularBase" ],
      [ "TriangularView", "classEigen_1_1TriangularView.html", "classEigen_1_1TriangularView" ],
      [ "TriangularViewImpl< _MatrixType, _Mode, Dense >", "classEigen_1_1TriangularViewImpl_3_01__MatrixType_00_01__Mode_00_01Dense_01_4.html", "classEigen_1_1TriangularViewImpl_3_01__MatrixType_00_01__Mode_00_01Dense_01_4" ],
      [ "TriangularViewImpl< MatrixType, Mode, Sparse >", "classEigen_1_1TriangularViewImpl_3_01MatrixType_00_01Mode_00_01Sparse_01_4.html", "classEigen_1_1TriangularViewImpl_3_01MatrixType_00_01Mode_00_01Sparse_01_4" ],
      [ "Tridiagonalization", "classEigen_1_1Tridiagonalization.html", "classEigen_1_1Tridiagonalization" ],
      [ "Triplet", "classEigen_1_1Triplet.html", "classEigen_1_1Triplet" ],
      [ "UmfPackLU", "classEigen_1_1UmfPackLU.html", "classEigen_1_1UmfPackLU" ],
      [ "UniformScaling", "classEigen_1_1UniformScaling.html", "classEigen_1_1UniformScaling" ],
      [ "VectorBlock", "classEigen_1_1VectorBlock.html", "classEigen_1_1VectorBlock" ],
      [ "VectorwiseOp", "classEigen_1_1VectorwiseOp.html", "classEigen_1_1VectorwiseOp" ],
      [ "WithFormat", "classEigen_1_1WithFormat.html", null ]
    ] ]
];