var searchData=
[
  ['skyline_20module_2967',['Skyline module',['../group__Skyline__Module.html',1,'']]],
  ['slicing_20and_20indexing_2968',['切分和索引',['../../group__TutorialSlicingIndexing.html',1,'']]],
  ['solving_20linear_20least_20squares_20systems_2969',['求解线性最小二乘方程组',['../../group__LeastSquares.html',1,'']]],
  ['solving_20sparse_20linear_20systems_2970',['求解稀疏线性系统',['../../group__TopicSparseSystems.html',1,'']]],
  ['space_20transformations_2971',['空间变换',['../../group__TutorialGeometry.html',1,'']]],
  ['sparse_20linear_20algebra_2972',['稀疏线性代数',['../../group__Sparse__chapter.html',1,'']]],
  ['sparse_20matrix_20manipulations_2973',['稀疏矩阵操作',['../../group__TutorialSparse.html',1,'']]],
  ['sparse_20meta_2dmodule_2974',['Sparse meta-module',['../../group__Sparse__Module.html',1,'']]],
  ['sparsecholesky_20module_2975',['SparseCholesky module',['../../group__SparseCholesky__Module.html',1,'']]],
  ['sparsecore_20module_2976',['SparseCore module',['../../group__SparseCore__Module.html',1,'']]],
  ['sparseextra_20module_2977',['SparseExtra module',['../group__SparseExtra__Module.html',1,'']]],
  ['sparselu_20module_2978',['SparseLU module',['../../group__SparseLU__Module.html',1,'']]],
  ['sparseqr_20module_2979',['SparseQR module',['../../group__SparseQR__Module.html',1,'']]],
  ['special_20math_20functions_20module_2980',['Special math functions module',['../group__SpecialFunctions__Module.html',1,'']]],
  ['spline_20and_20spline_20fitting_20module_2981',['Spline and spline fitting module',['../group__Splines__Module.html',1,'']]],
  ['stl_20iterators_20and_20algorithms_2982',['STL 迭代器和算法',['../../group__TutorialSTL.html',1,'']]],
  ['storage_20orders_2983',['存储指令',['../../group__TopicStorageOrders.html',1,'']]],
  ['structures_20having_20eigen_20members_2984',['Structures Having Eigen Members',['../../group__TopicStructHavingEigenMembers.html',1,'']]],
  ['suitesparseqr_20module_2985',['SuiteSparseQR module',['../../group__SPQRSupport__Module.html',1,'']]],
  ['superlusupport_20module_2986',['SuperLUSupport module',['../../group__SuperLUSupport__Module.html',1,'']]],
  ['support_20modules_2987',['Support modules',['../../group__Support__modules.html',1,'']]],
  ['svd_20module_2988',['SVD module',['../../group__SVD__Module.html',1,'']]]
];
